### ISSUE TITLE
Powershell 5.1 support

### ISSUE THREAD

**Issue by filimonic** [austineric/Send-MailKitMessage#22]
This line stops module from loading because it uses ternary operator introduced in Powershell 7

https://github.com/austineric/Send-MailKitMessage/blob/5a1316618ded262f82ad5f71b2a03a198aa339d5/Send-MailKitMessage.psm1#L85

If the rest is useable under PS5, please fix this.

**Comment by viniciusvillas** [comment]
Confirmed: this is the only thing preventing it from working in 5.1.
Ugly but simple workaround:
```
#smtp send
$Client=New-Object MailKit.Net.Smtp.SmtpClient
if ($UseSecureConnectionIfAvailable.IsPresent) {
	$Options = [MailKit.Security.SecureSocketOptions]::Auto
}
else {
	$Options = [MailKit.Security.SecureSocketOptions]::None
}
$Client.Connect($SMTPServer, $Port, $Options)
```

**Comment by austineric** [comment]
Better late than never 😀, version 3.2.0-preview1 adds Windows PowerShell support
https://www.powershellgallery.com/packages/Send-MailKitMessage/3.2.0-preview1
