### ISSUE TITLE
Credential is unsecure

### ISSUE THREAD

**Issue by fward1208** [austineric/Send-MailKitMessage#23]
Instead of using 

`$Client.Authenticate($Credential.UserName, ($Credential.Password | ConvertFrom-SecureString -AsPlainText))`

you may use

`$ADUserCredential = New-Object -TypeName System.Management.Automation.PSCredential -ArgumentList $ADCredUsername,$SecureStringPassword`

This is much more secure.

In order to create the password file, set variables, and run the command line below

`$EncryptedPasswordFile = '/home/some/path/password.txt'`
`$SecureStringPassword = Get-Content -Path $EncryptedPasswordFile | ConvertTo-SecureString`

`Read-Host -AsSecureString | ConvertFrom-SecureString | Out-File -FilePath $EncryptedPasswordFile`

Perhaps this is a limitation of the MailKit library in use?

**Comment by austineric** [comment]
Hi @fward1208,

Note that $Credential.Username and $Credential.Password come from the $Credential module parameter which is of type System.Management.Automation.PSCredential (see https://github.com/austineric/Send-MailKitMessage/blob/5a1316618ded262f82ad5f71b2a03a198aa339d5/Send-MailKitMessage.psm1#L12).

An example of creating the credential object can be found in the usage readme at https://github.com/austineric/Send-MailKitMessage#usage.
The credentials could be, as in your example, supplied manually or from a secure credential store.

I'm going to close this issue, but if I'm missing something feel free to reopen.
Thanks for the input!

Eric
