### ISSUE TITLE
Install fails

### ISSUE THREAD

**Issue by MihaIvan** [austineric/Send-MailKitMessage#28]
I used the command shown for installation. I got a prompt asking if I want to install and import the NuGet provider now. I responded Yes. Here is the contents of the command and output:
PS C:\Windows\system32> install-module -Name "Send-MailKitMessage" -scope AllUsers
WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' 
to ''.
WARNING: Unable to download the list of available providers. Check your internet connection.
PackageManagement\Install-PackageProvider : No match was found for the specified search criteria 
for the provider 'NuGet'. The package provider requires 'PackageManagement' and 'Provider' tags. 
Please check if the specified package has the tags.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7405 char:21
+ ...     $null = PackageManagement\Install-PackageProvider -Name $script:N ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Power...PackageProvider:InstallPackage 
   Provider) [Install-PackageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForProvider,Microsoft.PowerShell.PackageManagement.Cmd 
   lets.InstallPackageProvider
 
PackageManagement\Import-PackageProvider : No match was found for the specified search criteria 
and provider name 'NuGet'. Try 'Get-PackageProvider -ListAvailable' to see if the provider 
exists on the system.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7411 char:21
+ ...     $null = PackageManagement\Import-PackageProvider -Name $script:Nu ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (NuGet:String) [Import-PackageProvider], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmd 
   lets.ImportPackageProvider
 
WARNING: Unable to download from URI 'https://go.microsoft.com/fwlink/?LinkID=627338&clcid=0x409' 
to ''.
WARNING: Unable to download the list of available providers. Check your internet connection.
PackageManagement\Get-PackageProvider : Unable to find package provider 'NuGet'. It may not be 
imported yet. Try 'Get-PackageProvider -ListAvailable'.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:7415 char:30
+ ... tProvider = PackageManagement\Get-PackageProvider -Name $script:NuGet ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power...PackageProvider:GetPackageProvi 
   der) [Get-PackageProvider], Exception
    + FullyQualifiedErrorId : UnknownProviderFromActivatedList,Microsoft.PowerShell.PackageManag 
   ement.Cmdlets.GetPackageProvider
 
install-module : NuGet provider is required to interact with NuGet-based repositories. Please 
ensure that '2.8.5.201' or newer version of NuGet provider is installed.
At line:1 char:1
+ install-module -Name "Send-MailKitMessage" -scope AllUsers
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Install-Module], InvalidOperationException
    + FullyQualifiedErrorId : CouldNotInstallNuGetProvider,Install-Module

**Comment by austineric** [comment]
Hi @MihaIvan,
That isn't a Send-MailKitMessage error, that is a PowerShell error message.
There is lots of information out there on possible resolutions if you do a search on "Unable to download the list of available providers. Check your internet connection.".

One thing to note: are you running an updated version of PowerShell (currently 7.2.6)? If not you can install it from here: https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-on-windows?view=powershell-7.2#installing-the-msi-package
Send-MailKitMessage is designed to work with PowerShell 6+, if you need to use it with Windows PowerShell there is a preview version of the module available which adds support for Windows PowerShell: https://www.powershellgallery.com/packages/Send-MailKitMessage/3.2.0-preview1
