### ISSUE TITLE
When might version 3.2.0 be released?

### ISSUE THREAD

**Issue by stevenvolckaert** [austineric/Send-MailKitMessage#33]
Hello,

I'm using Send-MailKitMessage to send some emails from PowerShell scripts. Most of the machines these scripts run on, don't have pwsh.exe however, so I must install version 3.2.0-preview1, which forces me to update `PowerShellGet`.

It would be helpful if I would not be obliged to update PowerShellGet.

Any idea when Send-MailKitMessage version 3.2.0 might become available (version 3.2.0-preview1 is available since 8 November 2021).

**Comment by austineric** [comment]
Thanks for asking, 3.2.0 has been released.

**Comment by stevenvolckaert** [comment]
That's great, thank you @austineric!
